# Generated by Django 5.1.6 on 2025-03-09 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app4', '0001_initial'),
    ]

    operations = [
    ]
