# Generated by Django 5.1.6 on 2025-03-09 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app4', '0002_auto_20250309_0940'),
    ]

    operations = [
    ]
