# Generated by Django 5.1.6 on 2025-03-09 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app4', '0003_auto_20250309_0941'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='submitted_at',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='category',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='rating',
        ),
        migrations.AddField(
            model_name='feedback',
            name='event_rating',
            field=models.IntegerField(default=0),
        ),
    ]
